// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Author struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Comment struct {
	ID        int32
	PostID    sql.NullInt32
	AuthorID  sql.NullInt32
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Post struct {
	ID        int32
	Title     string
	Content   string
	AuthorID  sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PostTag struct {
	PostID int32
	TagID  int32
}

type Tag struct {
	ID   int32
	Name string
}
