// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Content struct {
	ID          int64
	ContentType string
	Title       string
	Content     sql.NullString
	ImageUrl    sql.NullString
	Link        sql.NullString
	CreatedAt   string
	UpdatedAt   string
}
