// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createContent = `-- name: CreateContent :one
INSERT INTO content (content_type, title, content, image_url, link)
VALUES (?, ?, ?, ?, ?)
RETURNING id, content_type, title, content, image_url, link, created_at, updated_at
`

type CreateContentParams struct {
	ContentType string
	Title       string
	Content     sql.NullString
	ImageUrl    sql.NullString
	Link        sql.NullString
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, createContent,
		arg.ContentType,
		arg.Title,
		arg.Content,
		arg.ImageUrl,
		arg.Link,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.ContentType,
		&i.Title,
		&i.Content,
		&i.ImageUrl,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM content WHERE id = ?
`

func (q *Queries) DeleteContent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContent, id)
	return err
}

const getContentById = `-- name: GetContentById :one
SELECT id, content_type, title, content, image_url, link, created_at, updated_at FROM content WHERE id = ?
`

func (q *Queries) GetContentById(ctx context.Context, id int64) (Content, error) {
	row := q.db.QueryRowContext(ctx, getContentById, id)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.ContentType,
		&i.Title,
		&i.Content,
		&i.ImageUrl,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentByTitle = `-- name: GetContentByTitle :one
SELECT id, content_type, title, content, image_url, link, created_at, updated_at FROM content WHERE content_type = ? AND title = ?
`

type GetContentByTitleParams struct {
	ContentType string
	Title       string
}

func (q *Queries) GetContentByTitle(ctx context.Context, arg GetContentByTitleParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, getContentByTitle, arg.ContentType, arg.Title)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.ContentType,
		&i.Title,
		&i.Content,
		&i.ImageUrl,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentsByType = `-- name: GetContentsByType :many
SELECT id, content_type, title, content, image_url, link, created_at, updated_at FROM content WHERE content_type = ? ORDER BY updated_at DESC
`

func (q *Queries) GetContentsByType(ctx context.Context, contentType string) ([]Content, error) {
	rows, err := q.db.QueryContext(ctx, getContentsByType, contentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.ContentType,
			&i.Title,
			&i.Content,
			&i.ImageUrl,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContent = `-- name: UpdateContent :one
UPDATE content
SET content_type = ?, title = ?, content = ?, image_url = ?, link = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, content_type, title, content, image_url, link, created_at, updated_at
`

type UpdateContentParams struct {
	ContentType string
	Title       string
	Content     sql.NullString
	ImageUrl    sql.NullString
	Link        sql.NullString
	ID          int64
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, updateContent,
		arg.ContentType,
		arg.Title,
		arg.Content,
		arg.ImageUrl,
		arg.Link,
		arg.ID,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.ContentType,
		&i.Title,
		&i.Content,
		&i.ImageUrl,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
