name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: l-pdufour
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build
      run: nix build
    # - name: Run tests
      # run: nix run .#test
    - name: Build Docker image
      run: nix build .#container
    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker load < result
        docker push ldufour/goserver:latest
